name: Build Android APK

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Java 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        channel: 'stable'
        cache: true

    - name: Locate Flutter Project & Build
      run: |
        if [ -f "pubspec.yaml" ]; then
          echo "Flutter project found in root directory"
          PROJECT_DIR="."
        elif [ -d "flutter" ] && [ -f "flutter/pubspec.yaml" ]; then
          echo "Flutter project found in /flutter directory"
          PROJECT_DIR="flutter"
        else
          echo "Searching for pubspec.yaml..."
          PROJECT_DIR=$(dirname $(find . -maxdepth 3 -name "pubspec.yaml" | head -n 1))
        fi
        
        echo "Navigating to $PROJECT_DIR"
        cd $PROJECT_DIR
        flutter pub get
        flutter build apk --release --no-tree-shake-icons

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Dokaner-Hisab-App
        path: "**/build/app/outputs/flutter-apk/app-release.apk"
        
